<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceLib\ServiceLib.csproj" />
  </ItemGroup>

</Project>
